version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

#   ui:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: ui
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=production
#       - BACKEND_URL=http://backend:5173  # This allows the UI to communicate with the backend
#     depends_on:
#       - backend
#     restart: unless-stopped

# networks:
#   default:
#     driver: bridge