export const SONG_PICKING_DURATION_IN_SEC = 10;
export const SONG_GUESSING_DURATION_IN_SEC = 30;
export const INITIAL_GUESSING_DELAY_IN_MS = 5000;
export const DELAY_BETWEEN_SONGS_IN_MS = 3000;
export const POINTS_CALCULATION_BASE = 12;

export const DEFAULT_POINTS_LIMIT = 120;
